name: linuxserver-remmina
services:
  app:
    image: linuxserver/remmina:1.4.43@sha256:dfdd42dcff06bcaa39f86dbec52f6caba2c749ee1ea6ab48cabf200c01749a65
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/remmina/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverremmina/assets/icon.png
  title:
    en_US: Remmina (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverremmina
  version: "1.4.43"
  port_map: '3000'
