name: linuxserver-cura
services:
  app:
    image: linuxserver/cura:5.13.0@sha256:c331f2faee6f703390aaa3e2a829e180ca85d63659a71a8017f666dd520cdf32
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/cura/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservercura/assets/icon.png
  title:
    en_US: Cura (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservercura
  version: "5.13.0"
  port_map: '3000'
