name: linuxserver-changedetection.io
services:
  app:
    image: linuxserver/changedetection.io:0.60.4@sha256:f30078f185055ad9a3e6e30ba124fed820a8b70f81b246bf32d44ac0125b5d53
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
      PLAYWRIGHT_DRIVER_URL: ''
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/changedetection.io/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverchangedetectionio/assets/icon.png
  title:
    en_US: Changedetection. Io (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverchangedetectionio
  version: "0.60.3"
  port_map: '5000'
