name: linuxserver-changedetection.io
services:
  app:
    image: linuxserver/changedetection.io:0.60.4@sha256:a03304f37a9c3c783039fa6ed291fe3b9c90886ca38e94e59f6c87da8958b043
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      BASE_URL: ''
      PLAYWRIGHT_DRIVER_URL: ''
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/changedetection.io/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverchangedetectionio/assets/icon.png
  title:
    en_US: Changedetection. Io (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverchangedetectionio
  version: "0.60.3"
  port_map: '5000'
