name: linuxserver-boinc
services:
  app:
    image: linuxserver/boinc:8.2.8@sha256:3908bbd781135fce57d1c207af408796d34bae78a31ccad7f0b56393ed5966be
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      PASSWORD: ''
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8181
        published: 8181
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/boinc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverboinc/assets/icon.jpg
  title:
    en_US: Boinc (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverboinc
  version: "8.2.8"
  port_map: '8080'
