name: linuxserver-doublecommander
services:
  app:
    image: linuxserver/doublecommander:arm64v8-version-47f5ef2f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/doublecommander/config
        target: /config
      - type: bind
        source: /DATA/AppData/doublecommander/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdoublecommander/assets/icon.png
  title:
    en_US: Doublecommander (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverdoublecommander
  version: "0.0.1"
  port_map: '3000'
