name: linuxserver-audacity
services:
  app:
    image: linuxserver/audacity:4.0.0@sha256:b4914b350e6756c3d15afc706955b3243c3d7970aa08db874992e47e70cfc02b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/audacity/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveraudacity/assets/icon.png
  title:
    en_US: Audacity (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserveraudacity
  version: "4.0.0"
  port_map: '3000'
