name: linuxserver-nextcloud
services:
  app:
    image: linuxserver/nextcloud:34.0.4@sha256:95bc55374a57fa04c48f9f29b79e85ab027a4969d1d2f756a19a9957bf0c0574
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 443
        published: 443
        protocol: tcp
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/nextcloud/config
        target: /config
      - type: bind
        source: /DATA/AppData/nextcloud/data
        target: /data
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservernextcloud/assets/icon.png
  title:
    en_US: Nextcloud (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservernextcloud
  version: "34.0.3"
  port_map: '80'
