name: linuxserver-htpcmanager
services:
  app:
    image: linuxserver/htpcmanager:version-26a641bf@sha256:40a4fca919cf148c6b032b2bbfd3c81041754f5273ee58c7cdeb9b5c57f6598f
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 8085
        published: 8085
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/htpcmanager/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverhtpcmanager/assets/icon.png
  title:
    en_US: Htpcmanager (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverhtpcmanager
  version: "0.0.1"
  port_map: '8085'
