name: linuxserver-freetube
services:
  app:
    image: linuxserver/freetube:version-190523148
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/freetube/config
        target: /config
x-casaos:
  id: wisdomsky.linuxserver.linuxserverfreetube
  version: "0.0.1"
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfreetube/assets/icon.png
  title:
    en_US: Freetube
