name: linuxserver-minisatip
services:
  app:
    image: linuxserver/minisatip:2.0.102@sha256:55b7b46332e3a335f96d3453775681f8bbd11944f8e2a562317fa36949dbdd8d
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      RUN_OPTS: ''
    ports:
      - target: 8875
        published: 8875
        protocol: tcp
      - target: 554
        published: 554
        protocol: tcp
      - target: 1900
        published: 1900
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/minisatip/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverminisatip/assets/icon.png
  title:
    en_US: Minisatip (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverminisatip
  version: "2.0.101"
