name: linuxserver-orcaslicer
services:
  app:
    image: linuxserver/orcaslicer:2.4.2@sha256:f8dc203f6a70176ab11cf2c15e56d26d2807b6081082748ab32729c6e10f5d1a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/orcaslicer/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverorcaslicer/assets/icon.png
  title:
    en_US: Orcaslicer (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverorcaslicer
  version: "2.4.2"
  port_map: '3000'
