name: linuxserver-kimai
services:
  app:
    image: linuxserver/kimai:2.66.0@sha256:ff19734fbddb03a7c49224bfacbbad6583b28f4a5bea7f5c4c5f993d2b5380b0
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      APP_SECRET: ''
      DATABASE_URL: ''
      TRUSTED_HOSTS: ''
      TRUSTED_PROXIES: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/kimai/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverkimai/assets/icon.png
  title:
    en_US: Kimai (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverkimai
  version: "2.66.0"
  port_map: '80'
