name: linuxserver-znc
services:
  app:
    image: linuxserver/znc:1.10.2@sha256:9557bd30f19f792891ab0557b3ff5145f1b23cc8c47e828aeab7ce4d865b7456
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 6501
        published: 6501
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/znc/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverznc/assets/icon.png
  title:
    en_US: Znc (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverznc
  version: "1.10.2"
  port_map: '6501'
