name: linuxserver-chrome
services:
  app:
    image: linuxserver/chrome:153.0.8010@sha256:801c26f5f64d20296790ff2c2dba846ac8d0498c0b1561d53fd0b34a9e07af2e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CHROME_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/chrome/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverchrome/assets/icon.png
  title:
    en_US: Chrome (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverchrome
  version: "152.0.7977"
  port_map: '3000'
