name: linuxserver-ddclient
services:
  app:
    image: linuxserver/ddclient:4.0.0@sha256:f397138084b41ca9470438a80f2ff9971d27f622d5907bc3996581deb666b5c9
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/ddclient/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverddclient/assets/icon.png
  title:
    en_US: Ddclient (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverddclient
  version: "4.0.0"
  port_map: '80'
