name: linuxserver-grav
services:
  app:
    image: linuxserver/grav:2.1.2@sha256:c68228d67eaaab719a914f3633bda3b4dc358385ab54fb340094d201e568ac92
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/grav/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservergrav/assets/icon.png
  title:
    en_US: Grav (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservergrav
  version: "2.0.24"
  port_map: '80'
