name: linuxserver-filezilla
services:
  app:
    image: linuxserver/filezilla:3.69.6@sha256:154ce54ec35d9b74f41c6d88bd39944165819aa8bae17a4260e64877acd906e6
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/filezilla/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfilezilla/assets/icon.png
  title:
    en_US: Filezilla (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverfilezilla
  version: "3.69.6"
  port_map: '3000'
