name: linuxserver-xemu
services:
  app:
    image: linuxserver/xemu:0.8.134@sha256:03ffcf91c951edde5de933227e0a7d03f3fe45920e68c46bb05e62540a5de3cd
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/xemu/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverxemu/assets/icon.png
  title:
    en_US: Xemu (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverxemu
  version: "0.8.134"
  port_map: '3000'
