name: linuxserver-brave
services:
  app:
    image: linuxserver/brave:1.95.101@sha256:ce48cda730d32fd2f47b44a46e3e2328ff35b139d35c5af89cd67414a13278d5
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/brave/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverbrave/assets/icon.png
  title:
    en_US: Brave (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverbrave
  version: "1.94.121"
  port_map: '3000'
