name: linuxserver-faster-whisper
services:
  app:
    image: linuxserver/faster-whisper:3.8.0@sha256:526761688d9ea55d6a17d45f0e3d9c01aa2f5ffdc4c79024eb0d094502f6a7d8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DEBUG: ''
      LOCAL_ONLY: ''
      WHISPER_BEAM: ''
      WHISPER_LANG: ''
      WHISPER_MODEL: ''
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/faster-whisper/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverfasterwhisper/assets/icon.png
  title:
    en_US: Faster whisper (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverfasterwhisper
  version: "3.7.0"
  port_map: '10300'
