name: linuxserver-retroarch
services:
  app:
    image: linuxserver/retroarch:1.22.2@sha256:f69e4b45fc11e67f9134abcc21c3bfc8b7b68ba0eb344a54e63d246e64392178
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/retroarch/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverretroarch/assets/icon.png
  title:
    en_US: Retroarch (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverretroarch
  version: "1.22.2"
  port_map: '3000'
