name: linuxserver-darktable
services:
  app:
    image: linuxserver/darktable:25.6.1@sha256:78ddb1fbe244a872c251ff9d028788e032151d91ce6102f25c97123244e632b8
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/darktable/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverdarktable/assets/icon.png
  title:
    en_US: Darktable (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverdarktable
  version: "25.6.1"
  port_map: '3000'
