name: linuxserver-lychee
services:
  app:
    image: linuxserver/lychee:7.8.3@sha256:24518c1814845defcde478fed628d9cd31ff84e572418803ad119df30179e97b
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      DB_CONNECTION: ''
      DB_HOST: ''
      DB_PORT: ''
      DB_USERNAME: ''
      DB_PASSWORD: ''
      DB_DATABASE: ''
      APP_NAME: ''
      APP_URL: ''
      TRUSTED_PROXIES: ''
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/lychee/config
        target: /config
      - type: bind
        source: /DATA/AppData/lychee/pictures
        target: /pictures
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverlychee/assets/icon.png
  title:
    en_US: Lychee (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverlychee
  version: "7.8.3"
  port_map: '80'
