name: linuxserver-opera
services:
  app:
    image: linuxserver/opera:135.0.5973@sha256:05f133f7a6d0b67a21ab109de8eefdf7d3bcb609b6d00fe97c6b7ca9bb71564e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      OPERA_CLI: ''
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/opera/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserveropera/assets/icon.png
  title:
    en_US: Opera (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserveropera
  version: "135.0.5973"
  port_map: '3000'
