name: linuxserver-webstation
services:
  app:
    image: linuxserver/webstation:0.8.0-romm@sha256:44e5141431c7048536d7ed674bd00d72a50d643a816a63bfae113b265ea5364a
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/webstation/config
        target: /config
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxserverwebstation/assets/icon.png
  title:
    en_US: Webstation (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxserverwebstation
  version: "0.8.0-romm"
  port_map: '3000'
