name: linuxserver-mame
services:
  app:
    image: linuxserver/mame:version-0.289dfsg1-0@sha256:ef005895fb8e01fb2cf1e94a7c6b54bbdf7d486d4f5cba802a5d45d7b534f029
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
      - target: 3001
        published: 3001
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mame/config
        target: /config
      - type: bind
        source: /DATA/AppData/mame/mame:ro
        target: /mame:ro
x-casaos:
  main: app
  icon: https://cdn.jsdelivr.net/gh/runui/CasaOS-LinuxServer-AppStore@gh-pages/apps/wisdomsky.linuxserver.linuxservermame/assets/icon.png
  title:
    en_US: Mame (LinuxServer.io)
  id: wisdomsky.linuxserver.linuxservermame
  version: "0.0.1"
  port_map: '3000'
